export const translations = {
  en: {
    spin_wheel: 'Spin Wheel',
    admin_dashboard: 'Admin',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    error_invalid_credentials: 'Invalid email or password.',
    error_user_exists: 'User with this email already exists.',
    prompt_register: "Don't have an account? Register now.",
    prompt_login: 'Already have an account? Login.',
    dior_lucky_wheel: 'Dior Lucky Wheel',
    dior_program_info: 'Spin the wheel for a chance to win exclusive Dior prizes.',
    not_logged_in: 'Please log in to spin the wheel.',
    spin_limit_reached_timed: 'You can spin again on {time}.',
    spin_limit_reached: 'You have already spun the wheel this week. Please come back later.',
    better_luck_next_time: 'Better Luck Next Time!',
    congratulations: 'Congratulations!',
    miss_a_turn_message: "You've missed a turn. Don't worry, try again next time!",
    close: 'Close',
    you_won: "You've won:",
    fill_info_to_receive: 'Please fill in your information to receive your prize.',
    full_name: 'Full Name',
    address: 'Address',
    submit: 'Submit',
    spin_now: 'SPIN',
    winners_list: 'Winners List',
    no_winners_yet: 'No winners yet.',
    date: 'Date',
    name: 'Name',
    prize: 'Prize',
    clear_winners: 'Clear Winners History',
    confirm_clear_winners: 'Are you sure you want to delete all winner records? This action cannot be undone.',
    yes_clear: 'Yes, Clear All',
    cancel: 'Cancel',
    // New keys for Admin Page
    prize_management: 'Prize Management',
    user_list: 'User List',
    image_url: 'Image URL',
    weight_probability: 'Weight (Probability)',
    save_changes: 'Save Changes',
    changes_saved: 'Changes saved successfully!',
    click_to_expand: 'Click to expand',
    name_en: 'Name (EN)',
    name_fr: 'Name (FR)',
    name_vi: 'Name (VI)',
    export_winners: 'Export Winners',
    export_users: 'Export Users',
    general_settings: 'General Settings',
    default_language: 'Default Language',
    // Prize names
    prize_lip_glow: 'Dior Lip Glow',
    prize_miss_dior: 'Miss Dior Perfume',
    prize_miss_turn: 'Miss a Turn',
    prize_foundation: 'Dior Backstage Foundation',
    prize_jadore: 'J\'adore Eau de Parfum',
    prize_lip_maximizer: 'Dior Addict Lip Maximizer',
    prize_sauvage: 'Sauvage Elixir',
  },
  fr: {
    spin_wheel: 'Faire tourner la roue',
    admin_dashboard: 'Admin',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: 'S\'inscrire',
    email: 'Email',
    password: 'Mot de passe',
    error_invalid_credentials: 'Email ou mot de passe invalide.',
    error_user_exists: 'Un utilisateur avec cet email existe déjà.',
    prompt_register: 'Pas de compte? S\'inscrire maintenant.',
    prompt_login: 'Déjà un compte? Se connecter.',
    dior_lucky_wheel: 'Roue de la Chance Dior',
    dior_program_info: 'Faites tourner la roue pour avoir une chance de gagner des prix Dior exclusifs.',
    not_logged_in: 'Veuillez vous connecter pour faire tourner la roue.',
    spin_limit_reached_timed: 'Vous pourrez tourner à nouveau le {time}.',
    spin_limit_reached: 'Vous avez déjà tourné la roue cette semaine. Veuillez revenir plus tard.',
    better_luck_next_time: 'Meilleure chance la prochaine fois!',
    congratulations: 'Félicitations!',
    miss_a_turn_message: 'Vous avez passé votre tour. Ne vous inquiétez pas, réessayez la prochaine fois!',
    close: 'Fermer',
    you_won: 'Vous avez gagné:',
    fill_info_to_receive: 'Veuillez remplir vos informations pour recevoir votre prix.',
    full_name: 'Nom complet',
    address: 'Adresse',
    submit: 'Envoyer',
    spin_now: 'TOURNER',
    winners_list: 'Liste des gagnants',
    no_winners_yet: 'Aucun gagnant pour le moment.',
    date: 'Date',
    name: 'Nom',
    prize: 'Prix',
    clear_winners: 'Effacer l\'historique des gagnants',
    confirm_clear_winners: 'Êtes-vous sûr de vouloir supprimer tous les enregistrements de gagnants? Cette action est irréversible.',
    yes_clear: 'Oui, tout effacer',
    cancel: 'Annuler',
    // New keys for Admin Page
    prize_management: 'Gestion des prix',
    user_list: 'Liste des utilisateurs',
    image_url: 'URL de l\'image',
    weight_probability: 'Poids (Probabilité)',
    save_changes: 'Enregistrer les modifications',
    changes_saved: 'Modifications enregistrées avec succès!',
    click_to_expand: 'Cliquer pour déplier',
    name_en: 'Nom (EN)',
    name_fr: 'Nom (FR)',
    name_vi: 'Nom (VI)',
    export_winners: 'Exporter les gagnants',
    export_users: 'Exporter les utilisateurs',
    general_settings: 'Paramètres Généraux',
    default_language: 'Langue par Défaut',
    // Prize names
    prize_lip_glow: 'Dior Lip Glow',
    prize_miss_dior: 'Parfum Miss Dior',
    prize_miss_turn: 'Passer un tour',
    prize_foundation: 'Fond de Teint Dior Backstage',
    prize_jadore: 'J\'adore Eau de Parfum',
    prize_lip_maximizer: 'Dior Addict Lip Maximizer',
    prize_sauvage: 'Sauvage Elixir',
  },
  vi: {
    spin_wheel: 'Vòng Quay',
    admin_dashboard: 'Bảng Quản Trị',
    logout: 'Đăng xuất',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    email: 'Email',
    password: 'Mật khẩu',
    error_invalid_credentials: 'Email hoặc mật khẩu không hợp lệ.',
    error_user_exists: 'Người dùng với email này đã tồn tại.',
    prompt_register: 'Chưa có tài khoản? Đăng ký ngay.',
    prompt_login: 'Đã có tài khoản? Đăng nhập.',
    dior_lucky_wheel: 'Vòng Quay May Mắn Dior',
    dior_program_info: 'Quay vòng quay để có cơ hội nhận những phần quà độc quyền từ Dior.',
    not_logged_in: 'Vui lòng đăng nhập để quay.',
    spin_limit_reached_timed: 'Bạn có thể quay lại vào {time}.',
    spin_limit_reached: 'Bạn đã quay trong tuần này. Vui lòng quay lại sau.',
    better_luck_next_time: 'Chúc Bạn May Mắn Lần Sau!',
    congratulations: 'Chúc Mừng!',
    miss_a_turn_message: 'Bạn đã mất lượt. Đừng lo, hãy thử lại lần sau!',
    close: 'Đóng',
    you_won: 'Bạn đã trúng:',
    fill_info_to_receive: 'Vui lòng điền thông tin để nhận giải thưởng.',
    full_name: 'Họ và Tên',
    address: 'Địa chỉ',
    submit: 'Gửi',
    spin_now: 'QUAY',
    winners_list: 'Danh Sách Trúng Thưởng',
    no_winners_yet: 'Chưa có ai trúng thưởng.',
    date: 'Ngày',
    name: 'Tên',
    prize: 'Giải thưởng',
    clear_winners: 'Xóa Lịch Sử Trúng Thưởng',
    confirm_clear_winners: 'Bạn có chắc chắn muốn xóa toàn bộ lịch sử trúng thưởng không? Hành động này không thể hoàn tác.',
    yes_clear: 'Có, Xóa',
    cancel: 'Hủy',
     // New keys for Admin Page
    prize_management: 'Quản Lý Giải Thưởng',
    user_list: 'Danh Sách Người Dùng',
    image_url: 'URL Hình Ảnh',
    weight_probability: 'Trọng Số (Tỷ Lệ)',
    save_changes: 'Lưu Thay Đổi',
    changes_saved: 'Đã lưu thay đổi thành công!',
    click_to_expand: 'Nhấn để mở rộng',
    name_en: 'Tên (EN)',
    name_fr: 'Tên (FR)',
    name_vi: 'Tên (VI)',
    export_winners: 'Xuất DS Trúng Thưởng',
    export_users: 'Xuất DS Người Dùng',
    general_settings: 'Cài Đặt Chung',
    default_language: 'Ngôn Ngữ Mặc Định',
    // Prize names
    prize_lip_glow: 'Son Dior Lip Glow',
    prize_miss_dior: 'Nước Hoa Miss Dior',
    prize_miss_turn: 'Mất lượt',
    prize_foundation: 'Kem Nền Dior Backstage',
    prize_jadore: 'Nước Hoa J\'adore',
    prize_lip_maximizer: 'Son Dior Addict Lip Maximizer',
    prize_sauvage: 'Nước Hoa Sauvage Elixir',
  },
};